### PR TITLE
Ci test using GH actions

### PR DESCRIPTION
**Pull request by sarthakpati**

### CODE REVIEW

**Comment by Borda** [comment]
I think that you can add this badge CI Build and Run to README

**Comment by sarthakpati** [comment]
Thanks, I have added the corresponding DevOps badge. 😄

**Comment by Borda** [comment]
I think think that native MarkDown would be better
`CI Build and Run`

**Comment by sarthakpati** [comment]
> I think think that native MarkDown would be better
> `CI Build and Run`

Agree but do you know how to center-align using markdown?

**Comment by Borda** [comment]
```
<center>
![CI Build and Run](https://github.com/CBICA/HistoReg/workflows/CI%20Build%20and%20Run/badge.svg)
</center>
```

**Comment by sarthakpati** [comment]
> ```
> <center>
> CI Build and Run
> </center>
> ```

Somehow, I am not able to get it to display correctly... Anyway, will figure it out later, thanks! 😄

**Pull request merged**
